volumes:
  db-data:
    driver: local
  public:
    driver: local

services:
  postgres:
    image: postgres:16.2
    restart: no
    shm_size: 128mb
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./../src/sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/postgres/

  adminer:
    image: adminer:4.8.1
    restart: no
    ports:
      - ${DB_ADMIN_PORT}:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres

  nodejs:
    image: node:20.11.1
    restart: no
#    build: ../
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    depends_on:
      - postgres

  nginx:
    image: nginx:1.24.0-alpine
    restart: no
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./public:/usr/share/nginx/html
    depends_on:
      - nodejs
    links:
      - nodejs
