volumes:
  db-data:
    driver: local
  public:
    driver: local

services:
  mariadb:
    image: mariadb:10.6.17-focal
    restart: 'no'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db-data:/var/lib/mysql
      - ./../src/sql:/docker-entrypoint-initdb.d
    ports:
      - ${MARIADB_PORT}:${MARIADB_PORT}
    expose:
      - ${MARIADB_PORT}

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    restart: always
    ports:
      - ${MARIADB_ADMIN_PORT}:80
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=${MARIADB_PORT}
      - PMA_USER=${MARIADB_USER}
      - PMA_PASSWORD=${MARIADB_PASSWORD}
    depends_on:
      - mariadb

  nodejs:
    image: node:20.11.1
    restart: 'no'
    build: ../
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    depends_on:
      - mariadb

  nginx:
    image: nginx:1.24.0-alpine
    restart: 'no'
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./public:/usr/share/nginx/html
    depends_on:
      - nodejs
    links:
      - nodejs
